// Development QA only: stress the actual Arena announcement renderer and timers.
const {app,BrowserWindow}=require('electron');
const fs=require('node:fs');
const path=require('node:path');
const output=path.resolve('.cache',`announcement-qa-${Date.now()}`);
fs.mkdirSync(output,{recursive:true});app.setPath('userData',path.join(output,'profile'));
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const report={output,scope:'Isolated development renderer; direct announcement calls and a visible injected combo counter, not ordinary play.',errors:[]};
const deadline=setTimeout(()=>app.exit(1),45000);
app.whenReady().then(async()=>{
 let win;
 try{
  win=new BrowserWindow({width:1024,height:768,useContentSize:true,show:false,webPreferences:{offscreen:true,contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false}});win.webContents.setFrameRate(60);
  win.webContents.on('console-message',event=>{if(event.level==='error'||event.level===3)report.errors.push(event.message);});
  const evaluate=code=>win.webContents.executeJavaScript(code,true);
  const waitFor=async(code,label)=>{for(let i=0;i<120;i++){if(await evaluate(code))return;await delay(60);}throw new Error(label);};
  const snap=async name=>{await delay(180);fs.writeFileSync(path.join(output,`${name}.png`),(await win.webContents.capturePage()).toPNG());};
  await win.loadURL('http://127.0.0.1:3000/?renderqa=1');await waitFor("Boolean(window.__sunlitQA?.game.scene.isActive('MenuScene'))",'menu');
  await evaluate("localStorage.setItem('shadowlegion_tutorial_v4','done');window.__sunlitQA.game.scene.getScene('MenuScene').scene.start('ArenaScene',{mode:'campaign',stageId:1,operativeId:'ranger',freshRun:true});void 0;");
  await waitFor("window.__sunlitQA.game.scene.isActive('ArenaScene')&&window.__sunlitQA.game.scene.getScene('ArenaScene').upgrading",'draft');
  await evaluate("{const a=window.__sunlitQA.game.scene.getScene('ArenaScene');a.selectUpgrade(a.upgradeMgr.pickThree('wave',a.hero)[0],'wave');void 0;}");
  await waitFor("!window.__sunlitQA.game.scene.getScene('ArenaScene').announcement",'initial notice expired');
  report.burst=await evaluate("{const a=window.__sunlitQA.game.scene.getScene('ArenaScene'),refs=[];for(let i=0;i<48;i++){a.announce('花火派对 · '+i,0x8aa978,900,0);refs.push(a.announcement);}({activeReferences:refs.filter(n=>n.active).length,containers:a.children.getChildren().filter(o=>o.type==='Container'&&o.depth===150).length,lastText:a.announcement.list.find(o=>o.type==='Text').text})}");
  report.priority=await evaluate("{const a=window.__sunlitQA.game.scene.getScene('ArenaScene');a.announce('锁定冲锋 · 留意前方',0xb46b48,1000,2);const warning=a.announcement;for(let i=0;i<48;i++)a.announce('低优先级技能 '+i,0x99aa88,800,0);a.announce('普通来波',0xaabbaa,800,1);const retained=a.announcement===warning;a.announce('旅途结束 · 高优先级回信',0x426644,1000,3);const ending=a.announcement;a.announce('迟到的冲锋',0xaa5544,800,2);({warningRetained:retained,endingRetained:a.announcement===ending,priority:a.announcementPriority,containers:a.children.getChildren().filter(o=>o.type==='Container'&&o.depth===150).length,text:a.announcement.list.find(o=>o.type==='Text').text})}");
  await snap('01-priority-kept');await waitFor("window.__sunlitQA.game.scene.getScene('ArenaScene').announcement===null",'notice timer did not destroy container');
  report.expired=await evaluate("{const a=window.__sunlitQA.game.scene.getScene('ArenaScene');({priority:a.announcementPriority,containers:a.children.getChildren().filter(o=>o.type==='Container'&&o.depth===150).length})}");
  report.longest=await evaluate("(async()=>{const{STAGES}=await import('/data/stages.ts');const a=window.__sunlitQA.game.scene.getScene('ArenaScene');let max=null;for(const stage of STAGES){for(let i=0;i<stage.waves.length;i++){const w=stage.waves[i],msg=`${i+1}/${stage.waves.length} · ${w.name}\\n${w.hint}`.replace('\\\\n','\\n');a.announce(msg,0xad7841,1600,1);const text=a.announcement.list.find(o=>o.type==='Text');if(!max||text.height>max.height)max={stageId:stage.id,wave:i+1,text:msg,height:text.height};}}a.announce(max.text,0xad7841,3000,1);a.comboCount=30;a.comboResetTime=a.combatTime+10000;a.updateCombo(a.combatTime);a.waveMgr.spawnOne('tank',true,true,'橡果团长',0);a.drawBossHud();a.paused=true;a.physics.pause();const t=a.announcement.list.find(o=>o.type==='Text'),b=t.getBounds(),c=a.comboText.getBounds();return {...max,notice:{left:b.left-14,right:b.right+14,top:b.top-9,bottom:b.bottom+9},combo:{left:c.left,right:c.right,top:c.top,bottom:c.bottom},bossHudBottom:145,bossVisible:a.bossNameText.visible,clearOfTopHud:b.top-9>145,clearOfCombo:b.bottom+9<=c.top||b.top-9>=c.bottom||b.right+14<=c.left||b.left-14>=c.right,containers:a.children.getChildren().filter(o=>o.type==='Container'&&o.depth===150).length};})()");
  await snap('02-longest-wave-with-combo');
  report.actionHint=await evaluate("(async()=>{const{WAVE_UPGRADES,LEVEL_UPGRADES,EVOLUTION_INFO}=await import('/data/upgrades.ts');const{SKILLS}=await import('/data/skills.ts');const a=window.__sunlitQA.game.scene.getScene('ArenaScene');const candidates=['本次进度暂时无法保存；仍可继续游玩','影伴：营地交给我！','影伴：一起去散步！','和昨日的自己击掌！镜像切磋完成','镜像切磋开始：观察蓄力线，轻跃躲开昨日的自己','旅途印章 +3  ·  暖灯修复 15%  ·  灵感 +45','还差 100 点灵感，继续击退小捣蛋',...[...WAVE_UPGRADES,...LEVEL_UPGRADES].map(u=>'行囊添新 · '+u.name),...Object.values(EVOLUTION_INFO).map(e=>'绽放进阶 · '+e.name),...SKILLS.map(s=>'学会本领 · '+s.name)];let max=null;for(const text of candidates){a.showActionHint(text,true);const b=a.actionHint.getBounds();if(!max||b.height>max.height||b.height===max.height&&b.width>max.width)max={text,height:b.height,width:b.width};}a.showActionHint(max.text,true);const h=a.actionHint.getBounds(),t=a.announcement.list.find(o=>o.type==='Text').getBounds();return {candidates:candidates.length,...max,hint:{left:h.left,right:h.right,top:h.top,bottom:h.bottom},overlapsNotice:h.left<t.right+14&&h.right>t.left-14&&h.top<t.bottom+9&&h.bottom>t.top-9,clearOfBottomHud:h.bottom<684,clearOfSideHud:h.left>308&&h.right<900};})()");
  await snap('03-wave-and-action-hint');
  await evaluate("window.__sunlitQA.game.scene.getScene('ArenaScene').showActionHint('行囊添新 · 花火 · 派对加料',true);void 0;");await snap('04-representative-skill-feedback');
  report.checks={singleAfterBurst:report.burst.activeReferences===1&&report.burst.containers===1,priority:report.priority.warningRetained&&report.priority.endingRetained,expires:report.expired.priority===-1&&report.expired.containers===0,topHud:report.longest.clearOfTopHud&&report.longest.bossVisible,combo:report.longest.clearOfCombo,actionHint:!report.actionHint.overlapsNotice&&report.actionHint.clearOfBottomHud&&report.actionHint.clearOfSideHud};
  fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({output,checks:report.checks,longest:report.longest,errors:report.errors},null,2));clearTimeout(deadline);win.destroy();app.exit(Object.values(report.checks).every(Boolean)&&!report.errors.length?0:1);
 }catch(error){report.failure=String(error.stack||error);fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));console.error(report.failure);clearTimeout(deadline);win?.destroy();app.exit(1);}
});
